import { Product } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'ProWave Swim Briefs',
    description: 'Hydrodynamic performance swimwear designed for competitive athletes. Chlorine resistant fabric.',
    price: 45.00,
    stock: 12,
    brand: 'Speedster',
    category: 'Swimwear',
    image: 'https://picsum.photos/400/500?random=1',
    rating: 4.8,
    reviewsCount: 124
  },
  {
    id: '2',
    title: 'Azure Deep Goggles',
    description: 'Anti-fog, UV protection goggles with a wide field of vision. Perfect for open water.',
    price: 32.50,
    stock: 8,
    brand: 'AquaView',
    category: 'Goggles',
    image: 'https://picsum.photos/400/500?random=2',
    rating: 4.5,
    reviewsCount: 89
  },
  {
    id: '3',
    title: 'Cotton Basic Tee',
    description: '100% organic cotton t-shirt. Breathable, soft, and durable for everyday wear.',
    price: 25.00,
    stock: 50,
    brand: 'Basics',
    category: 'T-Shirts',
    image: 'https://picsum.photos/400/500?random=3',
    rating: 4.2,
    reviewsCount: 210
  },
  {
    id: '4',
    title: 'HydroGlid Racer',
    description: 'Professional racing jammer. Compression fit for muscle support and drag reduction.',
    price: 85.00,
    stock: 5,
    brand: 'Speedster',
    category: 'Swimwear',
    image: 'https://picsum.photos/400/500?random=4',
    rating: 4.9,
    reviewsCount: 56
  },
  {
    id: '5',
    title: 'ClearVision Pro',
    description: 'Titanium mirrored lenses for bright conditions. Customizable nose bridge.',
    price: 45.00,
    stock: 15,
    brand: 'AquaView',
    category: 'Goggles',
    image: 'https://picsum.photos/400/500?random=5',
    rating: 4.7,
    reviewsCount: 112
  },
  {
    id: '6',
    title: 'Urban Graphic Tee',
    description: 'Streetwear inspired graphic tee. Heavyweight cotton with a boxy fit.',
    price: 35.00,
    stock: 20,
    brand: 'UrbanStyle',
    category: 'T-Shirts',
    image: 'https://picsum.photos/400/500?random=6',
    rating: 4.4,
    reviewsCount: 78
  },
  {
    id: '7',
    title: 'Surf Rash Guard',
    description: 'UPF 50+ sun protection. Quick dry material for surfing and beach activities.',
    price: 40.00,
    stock: 30,
    brand: 'WaveRider',
    category: 'Swimwear',
    image: 'https://picsum.photos/400/500?random=7',
    rating: 4.6,
    reviewsCount: 45
  },
  {
    id: '8',
    title: 'Sprint Tech Suit',
    description: 'Elite level tech suit for sprinters. Maximum compression and water repellency.',
    price: 250.00,
    stock: 3,
    brand: 'Speedster',
    category: 'Swimwear',
    image: 'https://picsum.photos/400/500?random=8',
    rating: 5.0,
    reviewsCount: 12
  },
  {
    id: '9',
    title: 'Junior Swim Set',
    description: 'Complete set with cap, goggles, and trunks for young swimmers.',
    price: 55.00,
    stock: 25,
    brand: 'AquaKid',
    category: 'Swimwear',
    image: 'https://picsum.photos/400/500?random=9',
    rating: 4.5,
    reviewsCount: 200
  },
  {
    id: '10',
    title: 'Retro Aviator Tee',
    description: 'Vintage wash t-shirt with classic aviation print.',
    price: 28.00,
    stock: 18,
    brand: 'VintageThreads',
    category: 'T-Shirts',
    image: 'https://picsum.photos/400/500?random=10',
    rating: 4.3,
    reviewsCount: 65
  },
  {
    id: '11',
    title: 'Triathlon Wetsuit',
    description: 'Full sleeve wetsuit for open water swimming. Buoyancy panels for better position.',
    price: 350.00,
    stock: 2,
    brand: 'IronMan',
    category: 'Swimwear',
    image: 'https://picsum.photos/400/500?random=11',
    rating: 4.9,
    reviewsCount: 8
  },
  {
    id: '12',
    title: 'Anti-Fog Spray',
    description: 'Long lasting anti-fog solution for all lens types.',
    price: 12.00,
    stock: 100,
    brand: 'ClearView',
    category: 'Accessories',
    image: 'https://picsum.photos/400/500?random=12',
    rating: 4.1,
    reviewsCount: 340
  },
  {
    id: '13',
    title: 'Silicone Swim Cap',
    description: 'High grade silicone cap. Wrinkle free fit to reduce drag.',
    price: 15.00,
    stock: 60,
    brand: 'Speedster',
    category: 'Accessories',
    image: 'https://picsum.photos/400/500?random=13',
    rating: 4.6,
    reviewsCount: 150
  },
  {
    id: '14',
    title: 'Training Fins',
    description: 'Short blade fins for leg strength and kick tempo training.',
    price: 38.00,
    stock: 22,
    brand: 'AquaPower',
    category: 'Accessories',
    image: 'https://picsum.photos/400/500?random=14',
    rating: 4.7,
    reviewsCount: 95
  },
  {
    id: '15',
    title: 'Performance Polo',
    description: 'Moisture wicking polo shirt for coaches and staff.',
    price: 45.00,
    stock: 15,
    brand: 'TeamGear',
    category: 'T-Shirts',
    image: 'https://picsum.photos/400/500?random=15',
    rating: 4.4,
    reviewsCount: 40
  },
  {
    id: '16',
    title: 'Women\'s Racing Back',
    description: 'High neck racing swimsuit with open back for freedom of movement.',
    price: 95.00,
    stock: 10,
    brand: 'Speedster',
    category: 'Swimwear',
    image: 'https://picsum.photos/400/500?random=16',
    rating: 4.8,
    reviewsCount: 88
  },
  {
    id: '17',
    title: 'Kids Fun Goggles',
    description: 'Colorful goggles with soft seal for children.',
    price: 18.00,
    stock: 40,
    brand: 'AquaKid',
    category: 'Goggles',
    image: 'https://picsum.photos/400/500?random=17',
    rating: 4.5,
    reviewsCount: 130
  },
  {
    id: '18',
    title: 'Mesh Equipment Bag',
    description: 'Large mesh bag for carrying wet gear. Breathable and quick drying.',
    price: 22.00,
    stock: 35,
    brand: 'GearHaul',
    category: 'Accessories',
    image: 'https://picsum.photos/400/500?random=18',
    rating: 4.6,
    reviewsCount: 70
  },
  {
    id: '19',
    title: 'Long Sleeve Sun Tee',
    description: 'Lightweight long sleeve tee for sun protection.',
    price: 32.00,
    stock: 28,
    brand: 'SunGuard',
    category: 'T-Shirts',
    image: 'https://picsum.photos/400/500?random=19',
    rating: 4.3,
    reviewsCount: 55
  },
  {
    id: '20',
    title: 'Pro Nose Clip',
    description: 'Comfortable nose clip with soft pads and steel frame.',
    price: 8.00,
    stock: 80,
    brand: 'Speedster',
    category: 'Accessories',
    image: 'https://picsum.photos/400/500?random=20',
    rating: 4.0,
    reviewsCount: 90
  }
];